### ISSUE TITLE
Lists in Chapter 4

### ISSUE THREAD

**Issue by frankyzam** [PacktPublishing/Learning-C-by-Developing-Games-with-Unity-Seventh-Edition#1]
Hi,

I get the following warning when compiling:
Assets/Scripts/Lists.cs(16,41): error CS1503: Argument 2: cannot convert from 'int' to 'UnityEngine.Object'

This is my code:
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Lists : MonoBehaviour
{
    List<string> QuestPartyMembers = new List<string>()
    {
        "Grim the Barbarian",
        "Merlin the Wise",
        "Sterling the Knight"
    };
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log("Party Members: {0}", QuestPartyMembers.Count);  
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

Why I get this warning when using your example code?

**Comment by frankyzam** [comment]
using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Lists : MonoBehaviour
{
    List<string> QuestPartyMembers = new List<string>()
    {
        "Grim the Barbarian",
        "Merlin the Wise",
        "Sterling the Knight"
    };
    // Start is called before the first frame update
    void Start()
    {
        Debug.Log("Party Members: {0}", QuestPartyMembers.Count);  
    }

    // Update is called once per frame
    void Update()
    {
        
    }
}

**Comment by frankyzam** [comment]
<img width="675" alt="Bildschirm­foto 2022-12-26 um 12 36 47" src="https://user-images.githubusercontent.com/89153414/209544764-1cd39f5f-be1f-4777-bed2-42b725ac08db.png">

**Comment by hferrone** [comment]
Hi, you need to use Debug.LogFormat() instead of Debug.Log().

**Comment by frankyzam** [comment]
Thank you very much, my fault🫣

**Comment by hferrone** [comment]
No problem at all, happy to help!

**Comment by frankyzam** [comment]
Do you know where to compare my code with someone else who also did Hero's trial?

**Comment by hferrone** [comment]
Ah, good question - there is a link to the Discord channel for this book - a ton of other readers are on there (including myself) and there's always discussion going on :)
