### ISSUE TITLE
Discord?

### ISSUE THREAD

**Issue by Kalennienna** [PacktPublishing/Learning-C-by-Developing-Games-with-Unity-Seventh-Edition#2]
What is the link for the Discord? I have been having a very rough time with this book... I can't figure out where/what to do. For example: Chapter 4, when I am to add a new member to the team, 
QuestPartyMembers.Add("Craven the Necromancer");

Where do I add it? After the List<string> ? Or before the list of elements? Or after the list of elements? I would very much like to see the code written out somewhere. Maybe at the end of the book? That would be so helpful. Thanks

**Comment by hferrone** [comment]
Hi! The full code is in this repo - you can go to the chapter after the one you're reading and see the full final product in code. The Discord server link is https://discord.gg/W4vUKjKb.

**Comment by Kalennienna** [comment]
Stupid question number 2... what is a repo?

**Comment by Kalennienna** [comment]
Ah.... does repo mean GitHub repository?

**Comment by hferrone** [comment]
It absolutely does :) Each of the folders in the repo (https://github.com/PacktPublishing/Learning-C-by-Developing-Games-with-Unity-Seventh-Edition) hold the complete project for that chapter. You can download the entire thing by going to the link I posted and pressing the green 'Code' button in the upper-right hand corner or just checking the script files you want. Happy coding!
